substitutions:
  _HOST: '0.0.0.0'
  _PORT: '1234'
  _USER: 'USER'
  _PASSWORD: '*****'
  _DATABASE: 'db'
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-central2-docker.pkg.dev/global-timer-435514-r9/soltaartifactreggistry/docker-vpc:$SHORT_SHA','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-central2-docker.pkg.dev/global-timer-435514-r9/soltaartifactreggistry/docker-vpc:$SHORT_SHA']
  - name: google/cloud-sdk
    args: ['gcloud', 'compute', 'networks', 'vpc-access', 'connectors', 'create', 'serverless-vpc-connect','--network', 'solta-test', '--region', 'europe-central2',  '--range','10.8.0.0/28','--min-instances','2','--max-instances','3','--machine-type','f1-micro']
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'docker-vpc', 
           '--image=europe-central2-docker.pkg.dev/global-timer-435514-r9/soltaartifactreggistry/docker-vpc:$SHORT_SHA',
           '--set-env-vars=','_HOST=${_HOST},_PORT=${_PORT},_USER=${_USER},_PASSWORD=${_PASSWORD},_DATABASE=${_DATABASE}', 
           '--region', 'europe-central2',  '--vpc-connector', 'serverless-vpc-connect','--vpc-egress', 'all', '--allow-unauthenticated' ]
images:
  - europe-central2-docker.pkg.dev/global-timer-435514-r9/soltaartifactreggistry/docker-vpc:$SHORT_SHA
